name: Windows RDP
on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Download Ngrok
        run: |
          Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
          Expand-Archive ngrok.zip
      - name: Connect Ngrok
        run: .\ngrok\ngrok.exe config add-authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
      - name: Enable RDP
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
      - name: Create Tunnel
        run: Start-Process .\ngrok\ngrok.exe -ArgumentList "tcp 3389"
      - name: Wait for Tunnel
        run: |
          $url = ""
          Write-Host "Searching for Ngrok Tunnel..."
          while ($url -eq "") {
            Start-Sleep -Seconds 5
            try {
              $json = Invoke-RestMethod -Uri http://localhost:4040/api/tunnels
              $url = $json.tunnels[0].public_url
            } catch {}
          }
          Write-Host "=========================================="
          Write-Host "IP Address: $url"
          Write-Host "Username: runneradmin"
          Write-Host "Password: Monstar@123"
          Write-Host "=========================================="
          net user runneradmin Monstar@123 /add
          net localgroup administrators runneradmin /add
      - name: Keep Alive
        run: |
          while ($true) { Start-Sleep -Seconds 300 }
          
